name: SonarCloud Scanner

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven
      - name: Create env.properties file
        run: echo "${{ secrets.ENV_PROPERTIES }}" > env.properties
      - name: Analyze with Sonar
        run: mvn clean -B verify -Dstyle.color=always
      - name: Jacoco Report
        uses: madrapps/jacoco-report@v1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
