name: SonarCloud Analysis

on: pull_request

permissions:
  pull-requests: write

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=alexey-sidorov-dev_otus-java-basic-part-one
            -Dsonar.organization=alexey-sidorov-dev
          projectBaseDir: .